spring:
 datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    couchbase:
      env:
        timeouts:
          view:
mybatis:
  mapper-locations: classpath*:mapper/*.xml #扫描mybatis的mapper.xml文件
  type-aliases-package: com.test.demo.model #起别名，指向实体类的位置，可省略写mybatis的xml中的resultType的全路径，取代<typeAlias alias="Admin" type="com.ljy.maven_github_ssm.model.Admin"/>

thymeleaf:
  cache: false #关闭缓存
  mode: HTML5 #设置模板类型
  encoding: utf-8  #设置编码